"use client";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica" },
  header: {
    marginBottom: 20,
    borderBottom: "1px solid #e2e8f0",
    paddingBottom: 10,
  },
  title: { fontSize: 18, fontWeight: "bold", color: "#0f172a" },
  subtitle: { fontSize: 10, color: "#64748b", marginTop: 4 },
  table: { width: "100%" },
  tableRow: {
    flexDirection: "row" as const,
    borderBottom: "0.5px solid #e2e8f0",
    paddingVertical: 4,
  },
  tableHeader: {
    flexDirection: "row" as const,
    borderBottom: "1px solid #334155",
    paddingBottom: 6,
    marginBottom: 4,
  },
  cell: { flex: 1, paddingHorizontal: 4 },
  headerCell: {
    flex: 1,
    paddingHorizontal: 4,
    fontWeight: "bold",
    color: "#475569",
    fontSize: 9,
  },
  footer: {
    position: "absolute" as const,
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center" as const,
    fontSize: 8,
    color: "#94a3b8",
  },
});

interface ReportPdfProps {
  title: string;
  headers: string[];
  rows: string[][];
  generatedAt: string;
}

export function ReportPdf({
  title,
  headers,
  rows,
  generatedAt,
}: ReportPdfProps) {
  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>TUM 2026 — {title}</Text>
          <Text style={styles.subtitle}>Generated: {generatedAt}</Text>
        </View>
        <View style={styles.table}>
          <View style={styles.tableHeader}>
            {headers.map((h, i) => (
              <Text key={i} style={styles.headerCell}>
                {h}
              </Text>
            ))}
          </View>
          {rows.map((row, i) => (
            <View key={i} style={styles.tableRow}>
              {row.map((cell, j) => (
                <Text key={j} style={styles.cell}>
                  {cell}
                </Text>
              ))}
            </View>
          ))}
        </View>
        <Text style={styles.footer}>
          Generated by TUM2026 IT Admin Dashboard
        </Text>
      </Page>
    </Document>
  );
}
